### ISSUE TITLE
Causes overencumbrance in the side job Dream on

### ISSUE THREAD

**Issue by pinkisdumb** [MrSimbax/cp2077-mod-wardrobe-items-adder#6] opened 2023-10-09 05:12 UTC
When you try to retrieve your items in this job and you've added clothes to your wardrobe using this mod, those clothes will be in the locker and make you over encumbered when you loot the locker.  Any advice for a temporary fix?

**Comment by MrSimbax** [comment] 2023-10-09 18:58
I fail to see how my mod could possibly add items to some weird locker, as it only interacts with the wardrobe system. What made you think my mod is the cause? Did you test the locker with/without it?

Also, I don't recall such a locker in Dream On. I think you're talking about **Sweet Dreams**. From a quick google search it's a known bug in the base game still present in 2.0; it seems  that the locker gives some phantom items which make your character encumbered. Some possible [solutions](https://old.reddit.com/r/cyberpunkgame/comments/xl6cai/so_have_a_pretty_game_breaking_bug_that_happens/) include just reloading the save after picking up the items from the locker.

The only way I can see my mod and this bug being somehow related is if the wardrobe is somehow linked to the locker, and it for some reason contains not only your inventory but also your whole wardrobe. But even then it's not a bug in my mod, it's a bug in the base game.

**Comment by MrSimbax** [comment] 2023-10-28 13:25
Author didn't respond, I'm assuming this is a bug in the base game, hence it's out of scope of this mod to fix it.

**Closed as completed by MrSimbax** 2023-10-28 13:25 UTC
Labels: question, wontfix
