### ISSUE TITLE
Not working after reinstalling the game.

### ISSUE THREAD

**Issue by Rudolph2109** [MrSimbax/cp2077-mod-wardrobe-items-adder#1] opened 2023-03-08 22:52 UTC
Hello! 
I saw on Nexusmods that you prefer to be contacted here insted.
I am having some issues with getting the Wardrobe_Items_Adder to work in my game, and I can't for the life of me figure out what's wrong! 
Let me tell you what I've done so far.
I have used this mod basically since you first uploaded it on Nexusmods! Never had any issues with it, and it has just been working as intended the entire time! Good job btw.! 
But yesterday I had to resolve to the "nuclear solution" to fix my game (Whatever had happened to my game files, was not caused by your mod), because something had gone wrong somewhere and my game files including all of my saved games had been completely corrupted! 
And after re-installing my newly downloaded game, installing most of all the many mods I'm used to be playing the game with including yours, I just couldn't get it to work all of a sudden! I made sure, that both the version of your mod is the most recent as well as CET. Anything and everything is up to date! When I bring op the CET console window after launching the game, the window for the wardrobe_items_adder shows up like always just fine. So I went to the settings tab to enable the option for items being added to my wardrobe when player spawns, went back to the main tab and clicked "Add all items". But nothing happens. And by nothing, I mean nothing! Even CET. are not writing anything in the log when I do this!
I have tried deleting the mod from the game, launch the game without it, the quit the game again. Went to download the mod once again, in case something with files I already had was messed up. But no matter what I've done, it's the same thing as soon as I want to utilize it in game!

I hope that you might have a suggestion to what I should do to get it working again, because I got to say, I'm all out of ideas at this point!

**Comment by MrSimbax** [comment] 2023-03-08 23:50
Hi, that's right, it's because I had stopped visiting Nexusmods every day, and would probably miss the notification in case somebody reported a problem.

Regarding your issue, did you change the version of the game and/or CET and/or the mod itself, or are they the same as when it was still working? Updates could break things, in which case I'll have to update the mod probably. I haven't played Cyberpunk for a while so wouldn't know if it broke, in which case thanks for letting me know. I can test it myself no sooner than tomorrow unfortunately.

If the versions are the same... Weird issue considering it was working fine before. Might be able to help if you provide more info.

The window appears, so that means the mod is loaded properly but not doing anything for some reason. IIRC there are txt/log files in the mod's directory in case of errors, so if there is such file and it's non-empty, please upload it here.

In the advanced settings there is log level option, change it to debug/all/whatever it's called I don't remember, and try again. This will hopefully result in something useful in the CET console, in which case copy-paste its content here please.

Some additional questions. Does it work with default settings? Can you add a specific item? Do you use any other wardrobe mods?

**Comment by Rudolph2109** [comment] 2023-03-09 00:14
I already checked the .txt file the mods directory within the game files, unfortunately it was just blank. I checked it after every attempt I've made to make it work again, but it has been blank each and every time.
I also tried to change the settings for the mod in inside of the game to "All". Didn't make any difference either. Nothing is being output by CET.
The only thing I didn't try actually is to see if if can make items appear in the wardrobe by adding their individual spawn commands into the mod. I will check if that works now, and I'll report back in a few minutes about it!

And thank you for replying as well! I really do appreciate that! :)

**Comment by Rudolph2109** [comment] 2023-03-09 00:28
I just tried to add a few individual item codes to the mod-window, and then clicked "Add Listed Items".
But same result for this too. All I got was a big load of absolutely nothing.

Before you asked about the versions of my game and mods, which I forgot to give you an answer for.
Regarding the game, it's Version 1.61DLSS.
CET is the most recent release as well, downloaded from here on Github, just a few moments before I wrote you my first message.
And as for the mod itself: Your most recent upload to Github as well.
I've even tried to download the game, AGAIN to install it on another drive. Then change executable in GOG Galaxy to the second game directory, so It would launch a "clean" non-modded game, with the exception of CET and Wardrobe_Items_Adder as the only two mods installed to that copy of the game. 
And well... I think you guess what that resulted in. 
That's right, the same thing happening there too. I simply just don't understand why! It was working without a single issue for as long as I've known about it's existence! But now suddenly, nothing is working any longer except for the fact that the mods window actually does show in the game, but every single function it's supposed have, seems to have died somewhere along the way. It's very, very odd!

**Comment by MrSimbax** [comment] 2023-03-09 08:39
The fact that nothing is printed to the console and there are no txt logs is very worrying. Especially considering the fact the UI is working, so the mod seems to be installed correctly and loaded by CET.

I might prepare a special package for you which will print more to the console if I can't reproduce the issue.

I see somebody reported same issue on NexusMods, don't know if that's a different person, if yes, then *something* must have changed for it to have stopped working suddenly.

Meanwhile, you can try with older CET, I see there was an update in February, it could be the reason. Also, is there `config.lua` in the mod's directory? If yes, what's inside? Can you add an item manually with a console command like `Game.GetWardrobeSystem():StoreUniqueItemIDAndMarkNew(ItemID.new(TweakDBID.new("Items.Balaclava_01_basic_01")))`?

**Comment by MrSimbax** [comment] 2023-03-09 18:04
I just updated my game along with all my mods, CET included, reinstalled my mod, and... it's working fine. I am sorry, I can't reproduce your issue. And I'm running out of ideas.

I added some additional `Logger:info("...")` commands around the code after pressing the button. Try the following package and see what is printed in the console.

[wardrobe_items_adder_DEBUG.zip](https://github.com/MrSimbax/cp2077-mod-wardrobe-items-adder/files/10934587/wardrobe_items_adder_DEBUG.zip)

If still nothing, then I am at a loss. How can the UI still work and yet not react to buttons?

By the way, can you test any other CET mod with similar UI? Maybe something is wrong with your CET installation for some reason?

**Comment by MrSimbax** [comment] 2023-09-27 15:14
Closing as I can't reproduce and OP stopped responding.

**Closed as completed by MrSimbax** 2023-09-27 15:14 UTC
Labels: bug, question, not reproducible
