### ISSUE TITLE
Not adding clothes to new save.

### ISSUE THREAD

**Issue by EspadaActual** [MrSimbax/cp2077-mod-wardrobe-items-adder#2] opened 2023-03-11 03:10 UTC
I attempted reinstalling the mod and applying the fix from the previous issue, but have had no luck with getting the clothes in my wardrobe. I have also deleted the previous save (it was just a test run for mods I installed) which had the clothes added. Does the mod only add clothes to one save?
![bruh](https://user-images.githubusercontent.com/127576050/224461854-77e92466-d482-4388-a38c-7e954dd7c965.PNG)

**Comment by EspadaActual** [comment] 2023-03-11 03:29
Should also note that adding items individually doesn't work either.

**Comment by MrSimbax** [comment] 2023-03-11 13:18
I could not reproduce on new save on fresh installation of Cyberpunk 2077. The mod adds new clothes to the closet on any save, new or old.

From this screenshot, it seems that the script for some reason suddenly stopped after line https://github.com/MrSimbax/cp2077-mod-wardrobe-items-adder/blob/0e6b63cf6926896f21f978f68ac640efdedb231e/init.lua#L148 For the other person in #1, it seems it stops even earlier as they claim there is nothing in the console. What's even weirder, the debug logs with duplicates indicate that it actually worked the first time (and I assume you have disabled the blacklist).

If there is non-empty `.log` file in the mod's directory, please upload it. Otherwise, I'm sorry, but I have no idea what's happening. I'm going to tag both issues as not reproducible. Can't do much else about them. I don't think there is an issue with my code because, as I've said several times already, it works for me, and can't find any reason why it would suddenly stop working as there was no significant update of either CET or the game.

As a workaround, you can probably still use the one-liner from README to add any cloth you want, or just use `Game.AddToInventory`.

```
Game.GetWardrobeSystem():StoreUniqueItemIDAndMarkNew(ItemID.new(TweakDBID.new("ITEM_ID_HERE")))
```

**Comment by EspadaActual** [comment] 2023-03-11 16:47
Yeah this is weird. `.log` file is empty too.

**Comment by EspadaActual** [comment] 2023-03-11 19:42
Do you think it would work if there were a way to clear `gamedataClothing_Record`, if it's like a file that just tracks if I have a piece of clothing in my wardrobe?

**Comment by MrSimbax** [comment] 2023-03-11 23:34
No, this record is static and contains data for all clothes in the game. Clearing it would certainly break the game. Which is why I wouldn't follow this clue, something would be very wrong if this record was indeed empty so I heavily doubt there lies the issue. It would also not explain why adding specific items doesn't work either.

I've realized there might another source of logs which might hopefully contain something useful. Start the game, try to use the mod as previously, then upload `*.log` files located in `bin/x64/plugins/cyber_engine_tweaks/`, specifically `cyber_engine_tweaks.log` and `scripting.log` (and `wardrobe_items_adder.log` if it's somehow non-empty this time around).

**Comment by MrSimbax** [comment] 2023-09-27 15:14
Closing as I can't reproduce and OP stopped responding.

**Closed as completed by MrSimbax** 2023-09-27 15:14 UTC
Labels: bug, question, not reproducible
